# Generated by Django 2.2.7 on 2019-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('image_tub', models.CharField(max_length=300)),
                ('image_full', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('explanation', models.TextField()),
            ],
        ),
    ]
